### ISSUE TITLE
Visibility? Bug in 3.3.0-Beta

### ISSUE THREAD

**Issue by BerndJM** [fieldOfView/PrepareStageCompactor#2]
The selected material is not shown
![auswahl_004](https://user-images.githubusercontent.com/1837889/38502826-ca020624-3c10-11e8-8320-703edcf875b8.png)
However the selection works as expected.

**Comment by fieldOfView** [comment]
Known issue, I have to make a fixed version for 3.3. Thanks for reporting.

**Comment by fieldOfView** [comment]
Fixed version is in the works here:
https://github.com/fieldOfView/PrepareStageCompactor/tree/3.3

**Comment by fieldOfView** [comment]
Can you test http://files/fieldofview.com/cura/v4/PrepareStageCompactor.curaplugin ? Download the file, and drop it into a running Cura 3.3 window and finally restart Cura. This version is not compatible with Cura 3.2

**Comment by BerndJM** [comment]
It works, thank you.
Even if your link is not correct, should be:
http://files.fieldofview.com/cura/v4/PrepareStageCompactor.curaplugin
;-)
