### ISSUE TITLE
is it possible to hide items with theme only? 

### ISSUE THREAD

**Issue by filipgoc** [fieldOfView/PrepareStageCompactor#3]
@fieldOfView Hi!

Is it possible to hide the compatibility link/ warning with pure theme?
Is this why you made this a plugin? 

I'm just trying to understand better how I tweak themes this beyond margins and colors. 
Thanks!

**Comment by filipgoc** [comment]
This is what I mean: 
![image](https://user-images.githubusercontent.com/16858474/40487550-d7f6c586-5f64-11e8-9586-f0043ddbc1a0.png)

**Comment by fieldOfView** [comment]
That is not possible with theming alone. The plugin basically replaces the sidebar with a new one that does not have that link (and optimizes some other things that cannot be changed with theming alone).
